# Generated by Django 4.2.6 on 2023-11-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_profile1_delete_regmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='regimodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musr', models.CharField(max_length=20)),
                ('memail', models.EmailField(max_length=254)),
                ('mmob', models.IntegerField()),
                ('mdob', models.DateTimeField()),
                ('mqual', models.CharField(max_length=20)),
                ('mpas', models.CharField(max_length=20)),
            ],
        ),
    ]
