# Generated by Django 4.2.6 on 2023-11-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_regimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='jpostmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cemail', models.EmailField(max_length=254)),
                ('ctitle', models.CharField(max_length=20)),
                ('cwtyp', models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid')], max_length=20)),
                ('cjtyp', models.CharField(choices=[('half time', 'half time'), ('full time', 'full time')], max_length=20)),
                ('cjexp', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7')], max_length=10)),
            ],
        ),
    ]
